language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
# pre-build step to set language
before_install:
  - locale-gen en_US en_US.UTF-8 && dpkg-reconfigure locales
