version: 0.0
os: linux
files:
  - source: /
    destination: /opt/carminatiio/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1800
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server
      timeout: 90
      runas: ubuntu
