version: 0.0
os: linux
files:
  - source: /
    destination: /opt/carminatiio/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1800
#  ApplicationStart:
#    - location: scripts/start_server
#      timeout: 300
