branch-defaults:
  dev:
    environment: carminatiio-dev
global:
  application_name: carminatiio
  default_ec2_keyname: myKey
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Python 2.7
  default_region: us-east-1
  profile: null
  sc: git
